name: 'Push to `main` (Create Release)'

on:
  push:
    branches: ['master']
permissions: 
  contents: write

jobs:
  buildSiteAndPushToGithubPages:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK 11'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'temurin'
          java-version: 11
#       - name: "Cache SSG HTTP caches"
#         id: 'cache-http'
#         uses: 'actions/cache@v3'
#         with:
#           path: 'build/cache'
#           key: '${{ runner.os }}-primes'
      - name: 'Make gradle accessible to user'
        run: 'chmod +x ./gradlew'
      - name: 'Build Kotlin Compose/Web SPA'
        run: './gradlew build'
      - name: 'Deploy to GitHub Pages'
        uses: 'JamesIves/github-pages-deploy-action@v4.4.0'
        with:
          folder: 'build/distributions/'
          single-commit: true
          force: true
